// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQAN6CTe1pZrerkcUZL7ZXraUNRbtBiL0',
    appId: '1:373796642742:web:750c8d20911b30a82a6b17',
    messagingSenderId: '373796642742',
    projectId: 'signinauth-d4057',
    authDomain: 'signinauth-d4057.firebaseapp.com',
    storageBucket: 'signinauth-d4057.firebasestorage.app',
    measurementId: 'G-5PEJ8PEBJY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc50Itf1KDUn54VRWlx6DVWYGLtllezuI',
    appId: '1:373796642742:ios:63215c59d4b927392a6b17',
    messagingSenderId: '373796642742',
    projectId: 'signinauth-d4057',
    storageBucket: 'signinauth-d4057.firebasestorage.app',
    iosBundleId: 'com.nikhil.learnflutter.learnflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQAN6CTe1pZrerkcUZL7ZXraUNRbtBiL0',
    appId: '1:373796642742:web:0a7a328ac1e311932a6b17',
    messagingSenderId: '373796642742',
    projectId: 'signinauth-d4057',
    authDomain: 'signinauth-d4057.firebaseapp.com',
    storageBucket: 'signinauth-d4057.firebasestorage.app',
    measurementId: 'G-0ZNVZNJVSS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc50Itf1KDUn54VRWlx6DVWYGLtllezuI',
    appId: '1:373796642742:ios:63215c59d4b927392a6b17',
    messagingSenderId: '373796642742',
    projectId: 'signinauth-d4057',
    storageBucket: 'signinauth-d4057.firebasestorage.app',
    iosBundleId: 'com.nikhil.learnflutter.learnflutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9ZCAmnIphDZuc_VMJ_16iV0Ngf6GnuvI',
    appId: '1:373796642742:android:cf767ca3dab593fd2a6b17',
    messagingSenderId: '373796642742',
    projectId: 'signinauth-d4057',
    storageBucket: 'signinauth-d4057.firebasestorage.app',
  );

}